export type CityEntry = { name: string; country: string; code: string }

export const MAJOR_CITIES: CityEntry[] = [
  // Asia
  { name: 'Tokyo', country: 'Japan', code: 'JP' },
  { name: 'Delhi', country: 'India', code: 'IN' },
  { name: 'Shanghai', country: 'China', code: 'CN' },
  { name: 'Beijing', country: 'China', code: 'CN' },
  { name: 'Dhaka', country: 'Bangladesh', code: 'BD' },
  { name: 'Mumbai', country: 'India', code: 'IN' },
  { name: 'Osaka', country: 'Japan', code: 'JP' },
  { name: 'Chongqing', country: 'China', code: 'CN' },
  { name: 'Karachi', country: 'Pakistan', code: 'PK' },
  { name: 'Kinshasa', country: 'DR Congo', code: 'CD' },
  { name: 'Lagos', country: 'Nigeria', code: 'NG' },
  { name: 'Istanbul', country: 'Turkey', code: 'TR' },
  { name: 'Bangalore', country: 'India', code: 'IN' },
  { name: 'Guangzhou', country: 'China', code: 'CN' },
  { name: 'Manila', country: 'Philippines', code: 'PH' },
  { name: 'Shenzhen', country: 'China', code: 'CN' },
  { name: 'Seoul', country: 'South Korea', code: 'KR' },
  { name: 'Jakarta', country: 'Indonesia', code: 'ID' },
  { name: 'Lahore', country: 'Pakistan', code: 'PK' },
  { name: 'Chennai', country: 'India', code: 'IN' },
  { name: 'Kolkata', country: 'India', code: 'IN' },
  { name: 'Hyderabad', country: 'India', code: 'IN' },
  { name: 'Chengdu', country: 'China', code: 'CN' },
  { name: 'Nanjing', country: 'China', code: 'CN' },
  { name: 'Wuhan', country: 'China', code: 'CN' },
  { name: 'Ahmedabad', country: 'India', code: 'IN' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', code: 'VN' },
  { name: 'Hanoi', country: 'Vietnam', code: 'VN' },
  { name: 'Kuala Lumpur', country: 'Malaysia', code: 'MY' },
  { name: 'Yangon', country: 'Myanmar', code: 'MM' },
  { name: 'Bangkok', country: 'Thailand', code: 'TH' },
  { name: 'Singapore', country: 'Singapore', code: 'SG' },
  { name: 'Hong Kong', country: 'Hong Kong', code: 'HK' },
  { name: 'Taipei', country: 'Taiwan', code: 'TW' },
  { name: 'Riyadh', country: 'Saudi Arabia', code: 'SA' },
  { name: 'Baghdad', country: 'Iraq', code: 'IQ' },
  { name: 'Tehran', country: 'Iran', code: 'IR' },
  { name: 'Dubai', country: 'United Arab Emirates', code: 'AE' },
  { name: 'Abu Dhabi', country: 'United Arab Emirates', code: 'AE' },
  { name: 'Ankara', country: 'Turkey', code: 'TR' },
  { name: 'Tashkent', country: 'Uzbekistan', code: 'UZ' },
  { name: 'Almaty', country: 'Kazakhstan', code: 'KZ' },
  { name: 'Kabul', country: 'Afghanistan', code: 'AF' },
  { name: 'Kathmandu', country: 'Nepal', code: 'NP' },
  { name: 'Colombo', country: 'Sri Lanka', code: 'LK' },
  { name: 'Phnom Penh', country: 'Cambodia', code: 'KH' },
  { name: 'Vientiane', country: 'Laos', code: 'LA' },
  { name: 'Ulaanbaatar', country: 'Mongolia', code: 'MN' },
  { name: 'Pyongyang', country: 'North Korea', code: 'KP' },
  { name: 'Doha', country: 'Qatar', code: 'QA' },
  { name: 'Kuwait City', country: 'Kuwait', code: 'KW' },
  { name: 'Muscat', country: 'Oman', code: 'OM' },
  { name: 'Amman', country: 'Jordan', code: 'JO' },
  { name: 'Beirut', country: 'Lebanon', code: 'LB' },
  { name: 'Damascus', country: 'Syria', code: 'SY' },
  { name: 'Jerusalem', country: 'Israel', code: 'IL' },
  { name: 'Tel Aviv', country: 'Israel', code: 'IL' },
  { name: 'Yerevan', country: 'Armenia', code: 'AM' },
  { name: 'Baku', country: 'Azerbaijan', code: 'AZ' },
  { name: 'Tbilisi', country: 'Georgia', code: 'GE' },
  { name: 'Bishkek', country: 'Kyrgyzstan', code: 'KG' },
  { name: 'Dushanbe', country: 'Tajikistan', code: 'TJ' },
  { name: 'Ashgabat', country: 'Turkmenistan', code: 'TM' },
  { name: 'Kyoto', country: 'Japan', code: 'JP' },
  { name: 'Nagoya', country: 'Japan', code: 'JP' },
  { name: 'Sapporo', country: 'Japan', code: 'JP' },
  { name: 'Fukuoka', country: 'Japan', code: 'JP' },
  { name: 'Busan', country: 'South Korea', code: 'KR' },
  { name: 'Incheon', country: 'South Korea', code: 'KR' },
  { name: 'Chiang Mai', country: 'Thailand', code: 'TH' },
  { name: 'Phuket', country: 'Thailand', code: 'TH' },
  { name: 'Bali', country: 'Indonesia', code: 'ID' },
  { name: 'Surabaya', country: 'Indonesia', code: 'ID' },
  { name: 'Medan', country: 'Indonesia', code: 'ID' },
  { name: 'Bandung', country: 'Indonesia', code: 'ID' },
  // Europe
  { name: 'Moscow', country: 'Russia', code: 'RU' },
  { name: 'London', country: 'United Kingdom', code: 'GB' },
  { name: 'Paris', country: 'France', code: 'FR' },
  { name: 'Madrid', country: 'Spain', code: 'ES' },
  { name: 'Barcelona', country: 'Spain', code: 'ES' },
  { name: 'Rome', country: 'Italy', code: 'IT' },
  { name: 'Milan', country: 'Italy', code: 'IT' },
  { name: 'Berlin', country: 'Germany', code: 'DE' },
  { name: 'Hamburg', country: 'Germany', code: 'DE' },
  { name: 'Munich', country: 'Germany', code: 'DE' },
  { name: 'Frankfurt', country: 'Germany', code: 'DE' },
  { name: 'Cologne', country: 'Germany', code: 'DE' },
  { name: 'Amsterdam', country: 'Netherlands', code: 'NL' },
  { name: 'Brussels', country: 'Belgium', code: 'BE' },
  { name: 'Vienna', country: 'Austria', code: 'AT' },
  { name: 'Warsaw', country: 'Poland', code: 'PL' },
  { name: 'Kraków', country: 'Poland', code: 'PL' },
  { name: 'Budapest', country: 'Hungary', code: 'HU' },
  { name: 'Prague', country: 'Czech Republic', code: 'CZ' },
  { name: 'Bucharest', country: 'Romania', code: 'RO' },
  { name: 'Kyiv', country: 'Ukraine', code: 'UA' },
  { name: 'Saint Petersburg', country: 'Russia', code: 'RU' },
  { name: 'Minsk', country: 'Belarus', code: 'BY' },
  { name: 'Stockholm', country: 'Sweden', code: 'SE' },
  { name: 'Oslo', country: 'Norway', code: 'NO' },
  { name: 'Copenhagen', country: 'Denmark', code: 'DK' },
  { name: 'Helsinki', country: 'Finland', code: 'FI' },
  { name: 'Reykjavik', country: 'Iceland', code: 'IS' },
  { name: 'Dublin', country: 'Ireland', code: 'IE' },
  { name: 'Lisbon', country: 'Portugal', code: 'PT' },
  { name: 'Porto', country: 'Portugal', code: 'PT' },
  { name: 'Athens', country: 'Greece', code: 'GR' },
  { name: 'Thessaloniki', country: 'Greece', code: 'GR' },
  { name: 'Sofia', country: 'Bulgaria', code: 'BG' },
  { name: 'Zagreb', country: 'Croatia', code: 'HR' },
  { name: 'Dubrovnik', country: 'Croatia', code: 'HR' },
  { name: 'Belgrade', country: 'Serbia', code: 'RS' },
  { name: 'Sarajevo', country: 'Bosnia', code: 'BA' },
  { name: 'Skopje', country: 'North Macedonia', code: 'MK' },
  { name: 'Tirana', country: 'Albania', code: 'AL' },
  { name: 'Riga', country: 'Latvia', code: 'LV' },
  { name: 'Tallinn', country: 'Estonia', code: 'EE' },
  { name: 'Vilnius', country: 'Lithuania', code: 'LT' },
  { name: 'Zurich', country: 'Switzerland', code: 'CH' },
  { name: 'Geneva', country: 'Switzerland', code: 'CH' },
  { name: 'Bern', country: 'Switzerland', code: 'CH' },
  { name: 'Valletta', country: 'Malta', code: 'MT' },
  { name: 'Luxembourg City', country: 'Luxembourg', code: 'LU' },
  { name: 'Nicosia', country: 'Cyprus', code: 'CY' },
  { name: 'Ljubljana', country: 'Slovenia', code: 'SI' },
  { name: 'Bratislava', country: 'Slovakia', code: 'SK' },
  { name: 'Chisinau', country: 'Moldova', code: 'MD' },
  { name: 'Podgorica', country: 'Montenegro', code: 'ME' },
  { name: 'Pristina', country: 'Kosovo', code: 'XK' },
  { name: 'Manchester', country: 'United Kingdom', code: 'GB' },
  { name: 'Birmingham', country: 'United Kingdom', code: 'GB' },
  { name: 'Glasgow', country: 'United Kingdom', code: 'GB' },
  { name: 'Edinburgh', country: 'United Kingdom', code: 'GB' },
  { name: 'Lyon', country: 'France', code: 'FR' },
  { name: 'Marseille', country: 'France', code: 'FR' },
  { name: 'Nice', country: 'France', code: 'FR' },
  { name: 'Naples', country: 'Italy', code: 'IT' },
  { name: 'Turin', country: 'Italy', code: 'IT' },
  { name: 'Venice', country: 'Italy', code: 'IT' },
  { name: 'Florence', country: 'Italy', code: 'IT' },
  { name: 'Seville', country: 'Spain', code: 'ES' },
  { name: 'Valencia', country: 'Spain', code: 'ES' },
  { name: 'Bilbao', country: 'Spain', code: 'ES' },
  { name: 'Ibiza', country: 'Spain', code: 'ES' },
  { name: 'Santorini', country: 'Greece', code: 'GR' },
  { name: 'Mykonos', country: 'Greece', code: 'GR' },
  // Africa
  { name: 'Cairo', country: 'Egypt', code: 'EG' },
  { name: 'Alexandria', country: 'Egypt', code: 'EG' },
  { name: 'Nairobi', country: 'Kenya', code: 'KE' },
  { name: 'Johannesburg', country: 'South Africa', code: 'ZA' },
  { name: 'Cape Town', country: 'South Africa', code: 'ZA' },
  { name: 'Durban', country: 'South Africa', code: 'ZA' },
  { name: 'Pretoria', country: 'South Africa', code: 'ZA' },
  { name: 'Casablanca', country: 'Morocco', code: 'MA' },
  { name: 'Marrakech', country: 'Morocco', code: 'MA' },
  { name: 'Fez', country: 'Morocco', code: 'MA' },
  { name: 'Rabat', country: 'Morocco', code: 'MA' },
  { name: 'Tunis', country: 'Tunisia', code: 'TN' },
  { name: 'Algiers', country: 'Algeria', code: 'DZ' },
  { name: 'Tripoli', country: 'Libya', code: 'LY' },
  { name: 'Addis Ababa', country: 'Ethiopia', code: 'ET' },
  { name: 'Dar es Salaam', country: 'Tanzania', code: 'TZ' },
  { name: 'Zanzibar', country: 'Tanzania', code: 'TZ' },
  { name: 'Accra', country: 'Ghana', code: 'GH' },
  { name: 'Dakar', country: 'Senegal', code: 'SN' },
  { name: 'Abidjan', country: 'Côte d\'Ivoire', code: 'CI' },
  { name: 'Khartoum', country: 'Sudan', code: 'SD' },
  { name: 'Kampala', country: 'Uganda', code: 'UG' },
  { name: 'Lusaka', country: 'Zambia', code: 'ZM' },
  { name: 'Harare', country: 'Zimbabwe', code: 'ZW' },
  { name: 'Maputo', country: 'Mozambique', code: 'MZ' },
  { name: 'Antananarivo', country: 'Madagascar', code: 'MG' },
  { name: 'Luanda', country: 'Angola', code: 'AO' },
  { name: 'Douala', country: 'Cameroon', code: 'CM' },
  { name: 'Abuja', country: 'Nigeria', code: 'NG' },
  { name: 'Kano', country: 'Nigeria', code: 'NG' },
  { name: 'Ibadan', country: 'Nigeria', code: 'NG' },
  { name: 'Lomé', country: 'Togo', code: 'TG' },
  { name: 'Cotonou', country: 'Benin', code: 'BJ' },
  { name: 'Bamako', country: 'Mali', code: 'ML' },
  { name: 'Conakry', country: 'Guinea', code: 'GN' },
  { name: 'Freetown', country: 'Sierra Leone', code: 'SL' },
  { name: 'Monrovia', country: 'Liberia', code: 'LR' },
  // Americas
  { name: 'São Paulo', country: 'Brazil', code: 'BR' },
  { name: 'Mexico City', country: 'Mexico', code: 'MX' },
  { name: 'New York', country: 'United States', code: 'US' },
  { name: 'Buenos Aires', country: 'Argentina', code: 'AR' },
  { name: 'Rio de Janeiro', country: 'Brazil', code: 'BR' },
  { name: 'Bogotá', country: 'Colombia', code: 'CO' },
  { name: 'Lima', country: 'Peru', code: 'PE' },
  { name: 'Santiago', country: 'Chile', code: 'CL' },
  { name: 'Los Angeles', country: 'United States', code: 'US' },
  { name: 'Chicago', country: 'United States', code: 'US' },
  { name: 'Houston', country: 'United States', code: 'US' },
  { name: 'Phoenix', country: 'United States', code: 'US' },
  { name: 'Philadelphia', country: 'United States', code: 'US' },
  { name: 'San Antonio', country: 'United States', code: 'US' },
  { name: 'San Diego', country: 'United States', code: 'US' },
  { name: 'Dallas', country: 'United States', code: 'US' },
  { name: 'San Francisco', country: 'United States', code: 'US' },
  { name: 'Seattle', country: 'United States', code: 'US' },
  { name: 'Denver', country: 'United States', code: 'US' },
  { name: 'Miami', country: 'United States', code: 'US' },
  { name: 'Las Vegas', country: 'United States', code: 'US' },
  { name: 'Atlanta', country: 'United States', code: 'US' },
  { name: 'Boston', country: 'United States', code: 'US' },
  { name: 'Washington DC', country: 'United States', code: 'US' },
  { name: 'Toronto', country: 'Canada', code: 'CA' },
  { name: 'Montreal', country: 'Canada', code: 'CA' },
  { name: 'Vancouver', country: 'Canada', code: 'CA' },
  { name: 'Calgary', country: 'Canada', code: 'CA' },
  { name: 'Ottawa', country: 'Canada', code: 'CA' },
  { name: 'Caracas', country: 'Venezuela', code: 'VE' },
  { name: 'Quito', country: 'Ecuador', code: 'EC' },
  { name: 'Guayaquil', country: 'Ecuador', code: 'EC' },
  { name: 'La Paz', country: 'Bolivia', code: 'BO' },
  { name: 'Santa Cruz', country: 'Bolivia', code: 'BO' },
  { name: 'Asunción', country: 'Paraguay', code: 'PY' },
  { name: 'Montevideo', country: 'Uruguay', code: 'UY' },
  { name: 'Medellín', country: 'Colombia', code: 'CO' },
  { name: 'Cali', country: 'Colombia', code: 'CO' },
  { name: 'Cartagena', country: 'Colombia', code: 'CO' },
  { name: 'Guadalajara', country: 'Mexico', code: 'MX' },
  { name: 'Monterrey', country: 'Mexico', code: 'MX' },
  { name: 'Cancún', country: 'Mexico', code: 'MX' },
  { name: 'Havana', country: 'Cuba', code: 'CU' },
  { name: 'Santo Domingo', country: 'Dominican Republic', code: 'DO' },
  { name: 'San Juan', country: 'Puerto Rico', code: 'PR' },
  { name: 'Guatemala City', country: 'Guatemala', code: 'GT' },
  { name: 'San Salvador', country: 'El Salvador', code: 'SV' },
  { name: 'Tegucigalpa', country: 'Honduras', code: 'HN' },
  { name: 'Managua', country: 'Nicaragua', code: 'NI' },
  { name: 'San José', country: 'Costa Rica', code: 'CR' },
  { name: 'Panama City', country: 'Panama', code: 'PA' },
  { name: 'Kingston', country: 'Jamaica', code: 'JM' },
  { name: 'Port-au-Prince', country: 'Haiti', code: 'HT' },
  { name: 'Nassau', country: 'Bahamas', code: 'BS' },
  { name: 'Bridgetown', country: 'Barbados', code: 'BB' },
  { name: 'Port of Spain', country: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Belo Horizonte', country: 'Brazil', code: 'BR' },
  { name: 'Brasília', country: 'Brazil', code: 'BR' },
  { name: 'Salvador', country: 'Brazil', code: 'BR' },
  { name: 'Fortaleza', country: 'Brazil', code: 'BR' },
  { name: 'Manaus', country: 'Brazil', code: 'BR' },
  { name: 'Recife', country: 'Brazil', code: 'BR' },
  // Oceania
  { name: 'Sydney', country: 'Australia', code: 'AU' },
  { name: 'Melbourne', country: 'Australia', code: 'AU' },
  { name: 'Brisbane', country: 'Australia', code: 'AU' },
  { name: 'Perth', country: 'Australia', code: 'AU' },
  { name: 'Adelaide', country: 'Australia', code: 'AU' },
  { name: 'Auckland', country: 'New Zealand', code: 'NZ' },
  { name: 'Wellington', country: 'New Zealand', code: 'NZ' },
  { name: 'Christchurch', country: 'New Zealand', code: 'NZ' },
  { name: 'Port Moresby', country: 'Papua New Guinea', code: 'PG' },
  { name: 'Suva', country: 'Fiji', code: 'FJ' },
  { name: 'Nadi', country: 'Fiji', code: 'FJ' },
  { name: 'Honolulu', country: 'United States', code: 'US' },
  { name: 'Tahiti', country: 'French Polynesia', code: 'PF' },
  { name: 'Noumea', country: 'New Caledonia', code: 'NC' },
]
